import { defineAsyncComponent } from 'vue';
import { Component } from 'vue';

export const MODAL_COMPONENTS: { [componentName: string]: Component } = {
    ADDRESS_CREATE: defineAsyncComponent(() => import('@/pages/common/AddressCreate.vue')),
    ADDRESS_FIND: defineAsyncComponent(() => import('@/pages/common/AddressFind.vue')),
    EXCHANGE_OPTION_CHANGE: defineAsyncComponent(() => import('@/pages/mypage/order/exchange/OptionChange.vue')),
    ORDER_COUPON_APPLY: defineAsyncComponent(() => import('@/pages/order/Coupon.vue')),
    CANCEL_ORDER_ITEM_SELECT: defineAsyncComponent(() => import('@/pages/mypage/order/CancelOrderItemSelect.vue')),
    ORDER_ITEM_SELECT: defineAsyncComponent(() => import('@/pages/mypage/order/OrderItemSelect.vue')),
    REFUND_ACCOUNT: defineAsyncComponent(() => import('@/pages/mypage/modal/RefundAccount.vue')),
    CANCEL_REFUND_ACCOUNT: defineAsyncComponent(() => import('@/pages/mypage/modal/CancelRefundAccount.vue')),
    ADDRESS_LIST: defineAsyncComponent(() => import('@/pages/mypage/modal/AddressList.vue')),
    PURCHASE_CONFIRM: defineAsyncComponent(() => import('@/pages/mypage/modal/PurchaseConfirm.vue')),
    RECEIPT: defineAsyncComponent(() => import('@/pages/mypage/modal/Receipt.vue')),
    GUEST_LOGIN: defineAsyncComponent(() => import('@/pages/login/Guest.vue')),
    GUEST_ADDRESS_EDIT: defineAsyncComponent(() => import('@/pages/guestMypage/modal/AddressEdit.vue')),
    POLICY_DETAIL: defineAsyncComponent(() => import('@/pages/policy/Detail.vue')),
    COMPANY_ALL: defineAsyncComponent(() => import('@/pages/policy/CompanyList.vue')),
    QNA_EDIT: defineAsyncComponent(() => import('@/pages/mypage/modal/QnaEdit.vue')),
    SELLER_QNA_CREATE: defineAsyncComponent(() => import('@/pages/mypage/modal/SellerQnaCreate.vue')),
    SELLER_QNA_EDIT: defineAsyncComponent(() => import('@/pages/mypage/modal/SellerQnaEdit.vue')),
    REVIEW_CREATE: defineAsyncComponent(() => import('@/pages/mypage/modal/ReviewCreate.vue')),
    REVIEW_EDIT: defineAsyncComponent(() => import('@/pages/mypage/modal/ReviewEdit.vue')),
    PASSWORD_CHANGE: defineAsyncComponent(() => import('@/pages/mypage/modal/PasswordChange.vue')),
    CARD_BENEFIT:  defineAsyncComponent(() => import('@/pages/common/CardBenefit.vue')),
    POLICY_UNIPASS: defineAsyncComponent(() => import('@/pages/common/Unipass.vue')),
    DEGREE_360_IMAGES: defineAsyncComponent(() => import('@/components/goods/Degree360Image.vue')),
    GIVE_AWAY: defineAsyncComponent(() => import('@/components/goods/Giveaway.vue')),
    GIVE_AWAY_TARGET: defineAsyncComponent(() => import('@/components/modal/GiveawayTarget.vue')),
    WISHED_FOLDER: defineAsyncComponent(() => import('@/components/modal/goods/WishedFolder.vue')),
    GOODS_DETAIL_DOWNLOADABLE_COUPON: defineAsyncComponent(() => import('@/pages/goods/Coupon.vue')),
    SIZE_GUIDE_IMAGES: defineAsyncComponent(() => import('@/pages/common/SizeGuide.vue')),
    RAFFLE_GUIDE: defineAsyncComponent(() => import('@/components/modal/raffle/Guide.vue')),
    RAFFLE_WINNERS: defineAsyncComponent(() => import('@/components/modal/raffle/Winners.vue')),
    RAFFLE_ENTRY: defineAsyncComponent(() => import('@/components/modal/raffle/Entry.vue')),
    EXPERIENCEGROUP_REVIEW_CREATE: defineAsyncComponent(() => import('@/pages/specialEvent/experienceGroup/Create.vue')),
    GOODS_DETAIL_QNA_CREATE: defineAsyncComponent(() => import('@/pages/goods/QnaCreate.vue')),
    GOODS_DETAIL_QNA_EDIT: defineAsyncComponent(() => import('@/pages/goods/QnaEdit.vue')),
    GOODS_DETAIL_BEST_REVIEW: defineAsyncComponent(() => import('@/pages/goods/review/BestReviewDetail.vue')),
    GOODS_DETAIL_PHOTO_REVIEWS: defineAsyncComponent(() => import('@/pages/goods/review/PhotoReviews.vue')),
    PHOTO_REVIEW_DETAIL: defineAsyncComponent(() => import('@/pages/goods/review/PhotoReviewDetail.vue')),
    ZOOM_REVIEW_IMAGE: defineAsyncComponent(() => import('@/components/goods/ZoomImage.vue')),
    BLOCK_BANNER_LIST: defineAsyncComponent(() => import('@/components/block/modal/BannerList.vue')),
    RECENT_VIEW_GOODS: defineAsyncComponent(() => import('@/pages/goods/RecentViewGoods.vue')),
    RENEWAL_PASSWORD_CHANGE: defineAsyncComponent(() => import('@/pages/renewal/PasswordChange.vue')),
    BANNER_LIST: defineAsyncComponent(() => import('@/components/modal/BannerList.vue')),
}